from xpaths import *
from css import *

# List of site domain, XPath, and CSS bundles

bundlelifehacks = ['https://lifehacks.io', xpathslifehacks, csslifehacks]
bundleskinny = ['http://skinnytaste.com', xpathsskinny, cssskinny]
bundlehowstuffworks = ['https://howstuffworks.com', xpathshowstuffworks, csshowstuffworks]
bundlemirror = ['https://mirror.co.uk', xpathsmirror, cssmirror]
bundledelish = ['https://delish.com', xpathsdelish, cssdelish]
bundlektla = ['https://ktla.com', xpathsktla, cssktla]
bundlecosmo = ['https://cosmopolitan.com', xpathscosmo, csscosmo]
bundlehistory = ['https://historydaily.org', xpathshistory, csshistory]
bundlemlb = ['https://www.mlb.com', xpathsmlb, cssmlb]
bundlebuzzfeed = ['https://www.buzzfeed.com/kyledavis/this-quiz-will-accurately-determine-your-pets-zodiac-sign', xpathsbuzzfeed, cssbuzzfeed]
bundlewetter = ['https://www.wetteronline.de', xpathswetter, csswetter]
bundleweather = ['https://weather.com', xpathsweather, cssweather]
bundlefoodnetwork = ['https://foodnetwork.com', xpathsfoodnetwork, cssfoodnetwork]
bundlehonesttopaws = ['https://honesttopaws.com', xpathshonesttopaws, csshonesttopaws]
bundlecheatsheet = ['https://cheatsheet.com', xpathscheatsheet, csscheatsheet]
bundlecountryliving = ['https://countryliving.com', xpathscountryliving, csscountryliving]
bundlenypost = ['https://nypost.com/2019/08/13/aoc-goes-after-barstool-sports-head-dave-portnoy-over-anti-union-tweet/', xpathsnypost, cssnypost]
bundlehealthline = ['https://healthline.com', xpathshealthline, csshealthline]
bundlethesaurus = ['https://thesaurus.com', xpathsthesaurus, cssthesaurus]
bundlecheezburger = ['https://cheezburger.com', xpathscheezburger, csscheezburger]
bundlemoneyversed = ['https://moneyversed.com', xpathsmoneyversed, cssmoneyversed]
bundlelivingly = ['https://livingly.com', xpathslivingly, csslivingly]
bundlelocal = ['http://localhost:8000', xpathslocal, csslocal]
bundletwentytwowords = ['https://twentytwowords.com/woman-tragically-ripped-apart-by-shark-as-family-watch/', xpathstwentytwowords, csstwentytwowords]
bundlefoxnews = ['https://www.foxnews.com/media/trump-cnn-chris-cuomo-fredo', xpathsfoxnews, cssfoxnews]
bundlehomehacks = ['https://homehacks.co/20-organization-stations-need-home/',xpathshomehacks,csshomehacks]
bundledailymail = ['https://www.dailymail.co.uk/health/article-7352469/Woman-awarded-56-million-botched-spinal-surgery-left-quadriplegic.html', xpathsdailymail, cssdailymail]
bundleusatoday = ['https://usatoday.com',xpathsusatoday, cssusatoday]
bundlelegacy = ['http://www.legacy.com/news/culture-and-trends/article/netflixs-dead-to-me-explores-a-widows-grief-through-comedy', xpathslegacy, csslegacy]
bundlepostfun = ['http://www.postfun.com/strange/what-even-are-these-weird-thrift-store-findings/?view-all&chrome=1', xpathspostfun, csspostfun]
bundlecitationmachine = ['http://www.citationmachine.net', xpathscitationmachine, csscitationmachine]
bundlelivestly = ['http://livestly.com/if-aliens-do-exist-sanders-will-give-american-public-the-411/', xpathslivestly, csslivestly]
bundleguardian = ['https://www.theguardian.com/us',xpathsguardian,cssguardian]
bundlepopulareverything = ['https://populareverything.com/can-you-guess-these-celebrities-based-off-their-throwback-photo/', xpathspopulareverything, csspopulareverything]
